<!DOCTYPE html>
<!-- saved from url http://www.bootstraptor.com ####################################################################
Don't remove this attribution.
This template build on DevKit http://www.bootstraptor.com
under GPL license
##########################################################################
-->
<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta charset="utf-8">
	<title>Base page</title>

	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="author" content="">

	<!-- Le styles -->
	<link id="colors" href="assets/css/bootstrap.css" rel="stylesheet" >

	<link href="assets/css/bootstrap-responsive.css" rel="stylesheet">
	<link href="assets/css/jquery.mCustomScrollbar.css" rel="stylesheet">
	<!-- SOME THEMES FIX -->

	<!-- GOOGLE FONT-->
	{{ stylesheet_link('//fonts.googleapis.com/css?family=Roboto:400,300,700italic,700,500&amp;subset=latin,latin-ext', false) }}
	<!-- /GOOGLE FONT-->
	<style type="text/css">
		body {
			padding-top: 0px;
			padding-bottom: 40px;
			padding-top: 0px;
			padding-bottom: 0px;
			font-family: 'Roboto', sans-serif;

		}

		h1,h2,h3,h4,h5,h6{
			font-weight:200;
		}

		.navbar-inverse .navbar-inner{
			-webkit-border-radius: 0px;
				-moz-border-radius: 0px;
					border-radius: 0px;
					background:#282828;
					border:none;
			}

			.navbar-inner{
				-webkit-border-radius: 0px;
				-moz-border-radius: 0px;
				border-radius: 0px;
			}

			.page-header{
				border:none;
				padding: 10px 0px 0px;
				margin: 0px 0 0px;
			}
			.brand{

				margin-left:20px;
				font-weight:700;
				text-decoration:none;
			}

			.thumbnail{
				border:none;
				padding:0px;
				-webkit-border-radius: 0px;
				-moz-border-radius: 0px;
				border-radius: 0px;
				-webkit-box-shadow: none;
				-moz-box-shadow: none;
				box-shadow: none;
			}



		.well {
			min-height: 20px;
			padding: 19px;
			margin-bottom: 20px;

			/*border: 1px solid #e3e3e3;*/
			-webkit-border-radius: 0px;
			-moz-border-radius: 0px;
			border-radius: 0px;
			-webkit-box-shadow: none;
			-moz-box-shadow: none;
			box-shadow: none;
		}


		.nav-tabs > li > a {

			-webkit-border-radius: 0px;
			-moz-border-radius: 0px;
			border-radius: 0px;
		}

		p{
			text-align:justify;
			margin-right:10px;
		}

		.row-fluid.articles-grid .span6:nth-child(2n+1){
			margin-left:0px;
		} /* fixed bs margin when row-fluid grid*/

		.fixed-top{
			position:fixed;
			top:0px;
			bottom:0px;
			display:inline-block;
			max-width:370px;
			background:e0e0e0;
			barder:1px solid #dfdfdf;
			z-index:1030;
		}

		.tab-content .tab-pane{
			max-height:600px;
			position:relative;
			overflow:auto;
		}

		footer{
			padding-top:40px;
			margin-top:40px;
			border-top:1px solid #dedede;
		}
		.related-projects{
			padding-top:40px;
			margin-top:40px;

		}

			/*************** @media ******************/
		@media (max-width: 940px){
			.brand {
				display:block;
				text-align:center;
				font-size:26px;
			}
		}

		@media (max-width: 1200px) and (min-width: 940px){
			.fixed-top {
				max-width:300px;
			}
		}

		@media (max-width: 940px) and (min-width: 768px){
			.fixed-top {
				max-width:225px;
			}
		}

	</style>

	<link href="assets/css/font-awesome.min.css" rel="stylesheet">
	<!-- USE PREFIX fa- e.g (<i class="fa-icon-home"></i> -->

	<!--[if lt IE 7]>
		<link href="assets/css/font-awesome-ie7.min.css" rel="stylesheet">
	<![endif]-->
	<!-- Fav and touch icons -->
	<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
		<!--[if lt IE 9]>
			<script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
		<![endif]-->
	<!-- Le fav and touch icons -->
	<link rel="shortcut icon" href="assets/ico/favicon.ico">
	<link rel="apple-touch-icon-precomposed" sizes="144x144" href="assets/ico/apple-touch-icon-144-precomposed.png">
	<link rel="apple-touch-icon-precomposed" sizes="114x114" href="assets/ico/apple-touch-icon-114-precomposed.png">
	<link rel="apple-touch-icon-precomposed" sizes="72x72" href="assets/ico/apple-touch-icon-72-precomposed.png">
	<link rel="apple-touch-icon-precomposed" href="assets/ico/apple-touch-icon-57-precomposed.png">
</head>
<body>

{{ content() }}


<!--***********STYLE SWITCHER ****************-->
<link href="assets/css/switcher.css" rel="stylesheet">
	<div id="style-switcher" style="right: 0px;">
			<h2>Color Switcher Options<a href="#"><i class="fa-icon-cogs main-color"></i> Styles</a></h2>
			<div>
				<h3>Default Colors (includes Menu Hover)</h3>
				<div class="well">
				<ul>
						<li><a class="cyborg">cyborg</a></li>
					   <li><a class="readable">readable</a></li>
					   <li><a class="united">united</a></li>
					   <li><a class="journal">journal</a></li>
					   <li><a class="spruce">spruce</a></li>
					   <li><a class="spacelab">spacelab</a></li>
					   <li><a class="simplex">simplex</a></li>
					   <li><a class="slate">slate</a></li>
					   <li><a class="superhero">superhero</a></li>
					   <li><a class="flatly">flatly</a></li>


				</ul>
				</div>
				<!--Menu STYLES -->
			</div>
		<div id="reset"><a href="#" class="btn btn-info">Reset</a></div>
	</div>
	<!--*******************************-->
	<!--*****[End] style switcher *****-->
	<!--*******************************-->





	<!-- Le javascript
	================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="assets/js/jquery.js" type="text/javascript"></script>
<script src="assets/js/bootstrap-transition.js" type="text/javascript"></script>
<script src="assets/js/bootstrap-alert.js" type="text/javascript"></script>
<script src="assets/js/bootstrap-modal.js" type="text/javascript"></script>
<script src="assets/js/bootstrap-dropdown.js" type="text/javascript"></script>
<script src="assets/js/bootstrap-scrollspy.js" type="text/javascript"></script>
<script src="assets/js/bootstrap-tab.js" type="text/javascript"></script>
<script src="assets/js/bootstrap-tooltip.js" type="text/javascript"></script>
<script src="assets/js/bootstrap-popover.js" type="text/javascript"></script>
<script src="assets/js/bootstrap-button.js" type="text/javascript"></script>
<script src="assets/js/bootstrap-collapse.js" type="text/javascript"></script>
<script src="assets/js/bootstrap-carousel.js" type="text/javascript"></script>
<script src="assets/js/bootstrap-typeahead.js" type="text/javascript"></script>
<script src="assets/js/bootstrap-affix.js" type="text/javascript"></script>
<script src="assets/js/jquery.localscroll-1.2.7-min.js" type="text/javascript"></script>
<script src="assets/js/jquery.scrollTo-1.4.2-min.js" type="text/javascript"></script>
<script src="assets/js/jquery.mousewheel.js" type="text/javascript"></script>
<script src="assets/js/jquery.mCustomScrollbar.js" type="text/javascript"></script>

<!-- STYLE SWITCHER-->
<script type="text/javascript" src="assets/js/switcher.js"></script>

<script>
		var nav = jQuery('#left-side-menu');
		jQuery(window).scroll(function () {
				if (jQuery(this).scrollTop() > 197) {
					nav.addClass("fixed-top");
				} else {
					nav.removeClass("fixed-top");
				}
			});
</script>




<!--<script>
	(function($){
		$(window).load(function(){
			$(".tab-pane").mCustomScrollbar();


		});
	})(jQuery);
</script>-->

</body>
</html>